name: Deploy to Vercel
on:
  push:
    branches:
      - main # أو اسم الفرع الرئيسي عندك

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release --web-renderer html

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production

      - name: Build Project Artifacts
        run: vercel build --prod

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod